### ISSUE TITLE
Duplicate lines in bookshelf/configure.ac causing error when attempting to run autogen.sh

### ISSUE THREAD

**Issue by bowmanjc** [raspberrypi-ui/bookshelf#10]
Duplicate lines 2 & 6 (AC_CONFIG_MACRO_DIR([m4]) in bookshelf/configure.ac causing fatal error when attempting to run autogen.sh

```
AC_PREREQ(2.53)
AC_CONFIG_MACRO_DIR([m4])
AC_INIT(rp-bookshelf,1.0,http://raspberrypi.org/)
AM_INIT_AUTOMAKE([-Wall foreign subdir-objects no-dist-gzip dist-xz])
AC_CONFIG_HEADER([config.h])
AC_CONFIG_MACRO_DIR([m4])
```

**Comment by spl237** [comment]
![Untitled](https://user-images.githubusercontent.com/10401149/180661541-395b7a88-55c7-4c30-b743-16c38e1e6086.png)

Works fine for me under RPiOS. This seems to be a common mistake in Debian configure files, but doesn't seem to cause any issues. For what OS are you trying to build?

**Comment by bowmanjc** [comment]
Thanks Simon for following up on this! This is a great application, but I like having access to all of the RPi publications on my Fedora 36 (x86_64) desktop system.

As far as I can tell, there is no pre-built rpm package. So, I created an Ansible playbook to install the rpm dependencies, clone/update the git repo, and then step through building the application (autogen/configure/make/make install). However, it fails when executing autogen.sh due to the line duplication. If I remove the duplicate line and rerun the playbook starting at autogen.sh, it runs fine.

If you're interested, I'm happy to share my playbook. However, I still need to make a few refinements to make ansible-lint happy.

**Comment by spl237** [comment]
Given this bug doesn't affect RPiOS, it's not going to be a priority for us, and it will be in most of the configure files on this repo. I'll remove it as and when I update packages, but for now, it's probably best if you just fix it locally for your Fedora builds.
