### ISSUE TITLE
Re-add Wirecutter and Custom PC tabs to be able to see old issues

### ISSUE THREAD

**Issue by dimaguy** [raspberrypi-ui/bookshelf#13]
While I understand that wirecutter shutdown and custom pc was sold and is online now (as per https://forums.raspberrypi.com/viewtopic.php?t=350113) I still have a lot of their issues stored in my bookshelf directory, and I'd like to be able to browse through them using bookshelf, would that be possible?

**Comment by spl237** [comment]
I'm afraid not - our distribution agreement doesn't allow us to continue to offer these titles in Bookshelf.
