### ISSUE TITLE
rp-bookshelf tabs often stop reacting to touch events on a touchscreen

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi-ui/bookshelf#3]
rp-bookshelf tabs often stop reacting to touch events on a touchscreen.
arm64 version on raspberry pi OS. 
up-to-date at the time of bug opening.

**Comment by spl237** [comment]
There's nothing in the application that could cause this to happen - it's either a bug in the underlying GTK+3 toolkit, or a problem with the touchscreen or its software. Sorry, but there's nothing I'll be able to do to fix it in the application.

**Comment by mgrouch** [comment]
It looks like it’s using gtk2 in raspberry pi os arm64. If it were compiled with gtk3 there might be no that issue

**Comment by spl237** [comment]
Possibly. There will be a release built against GTK+3 in the near future.
